=== dzun/4711mcmaster/data/MaraudersRoster.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/MaraudersRoster.dtd
-->

<!--- Indicates that at least one player is nested inside players. -->
<!ELEMENT players (player)*>

<!--- Indicates that highschool,hometown,year,faculty_program,elig,weight,in.,
        ft.,position,last_name,first_name,number elements are required 
        for each player -->
<!ELEMENT player (number,first_name,last_name,position,ft.,in.,
        weight,elig,faculty_program,year,hometown,highschool)>

<!--- Defines the number data to be #PCDATA. -->
<!ELEMENT number (#PCDATA)>

<!--- Defines the first_name data to be #PCDATA. -->
<!ELEMENT first_name (#PCDATA)>

<!--- Defines the last_name data to be #PCDATA. -->
<!ELEMENT last_name (#PCDATA)>

<!--- Defines the position data to be #PCDATA. -->
<!ELEMENT position (#PCDATA)>

<!--- Defines the ft. data to be #PCDATA. -->
<!ELEMENT ft. (#PCDATA)>

<!--- Defines the in. data to be #PCDATA. -->
<!ELEMENT in. (#PCDATA)>

<!--- Defines the weight data to be #PCDATA. -->
<!ELEMENT weight (#PCDATA)>

<!--- Defines the elig data to be #PCDATA. -->
<!ELEMENT elig (#PCDATA)>

<!--- Defines the faculty_program data to be #PCDATA. -->
<!ELEMENT faculty_program (#PCDATA)>

<!--- Defines the year data to be #PCDATA. -->
<!ELEMENT year (#PCDATA)>

<!--- Defines the hometown data to be #PCDATA. -->
<!ELEMENT hometown (#PCDATA)>

<!--- Defines the highschool data to be #PCDATA. -->
<!ELEMENT highschool (#PCDATA)>

=== dzun/4711mcmaster/data/MaraudersRoster.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : MaraudersRoster.xml
    Created on : October 21, 2010, 5:18 AM
    Author     : alistair and daisy
    Description:
        Roster for the McMaster Marauders football team.
-->

<!DOCTYPE players SYSTEM 'MaraudersRoster.dtd'>

<players>
    <player>
        <number>1</number>
        <first_name>Michael</first_name>
        <last_name>Dicroce</last_name>
        <position>WR</position>
        <ft.>5</ft.>
        <in.>11</in.>
        <weight>192</weight>
        <elig>3</elig>
        <faculty_program>Social Sciences</faculty_program>
        <year>2</year>
        <hometown>Hamilton On</hometown>
        <highschool>Bishop Ryan Cath S S</highschool>
    </player>
    <player>
        <number>2</number>
        <first_name>Marshall</first_name>
        <last_name>Ferguson</last_name>
        <position>QB</position>
        <ft.>6</ft.>
        <in.>2</in.>
        <weight>200</weight>
        <elig>2</elig>
        <faculty_program>Political Science</faculty_program>
        <year>2</year>
        <hometown>Kingston On</hometown>
        <highschool>Frontenac S S</highschool>
    </player>
    <player>
        <number>3</number>
        <first_name>Trevor</first_name>
        <last_name>Gary</last_name>
        <position>LB</position>
        <ft.>6</ft.>
        <in.>1</in.>
        <weight>200</weight>
        <elig>4</elig>
        <faculty_program>Economics</faculty_program>
        <year>3</year>
        <hometown>Mississauga On</hometown>
        <highschool>Oakville Trafalgar H S</highschool>
    </player>
    <player>
        <number>4</number>
        <first_name>Tyler</first_name>
        <last_name>Crapigna</last_name>
        <position>K/P</position>
        <ft.>5</ft.>
        <in.>7</in.>
        <weight>156</weight>
        <elig>2</elig>
        <faculty_program>Environmental and Earth Science</faculty_program>
        <year>1</year>
        <hometown>Nepean On</hometown>
        <highschool>St Pauls Cath H S</highschool>
    </player>
    <player>
        <number>5</number>
        <first_name>Max</first_name>
        <last_name>Cameron</last_name>
        <position>WR</position>
        <ft.>6</ft.>
        <in.>1</in.>
        <weight>175</weight>
        <elig>1</elig>
        <faculty_program>Business</faculty_program>
        <year>1</year>
        <hometown>St Catharines On</hometown>
        <highschool>Sir Winston Churchill S S</highschool>
    </player>
    <player>
        <number>5</number>
        <first_name>Kasean</first_name>
        <last_name>Davis-Reynolds</last_name>
        <position>RB</position>
        <ft.>5</ft.>
        <in.>11</in.>
        <weight>190</weight>
        <elig>1</elig>
        <faculty_program>Social Sciences</faculty_program>
        <year>1</year>
        <hometown>Mississauga On</hometown>
        <highschool>St Francis Xavier S S</highschool>
    </player>
    <player>
        <number>6</number>
        <first_name>Dahlin</first_name>
        <last_name>Brooks</last_name>
        <position>WR</position>
        <ft.>6</ft.>
        <in.>1</in.>
        <weight>180</weight>
        <elig>2</elig>
        <faculty_program>Classics</faculty_program>
        <year>2</year>
        <hometown>Kitchener On</hometown>
        <highschool>Forest Heights C I</highschool>
    </player>
    <player>
        <number>7</number>
        <first_name>Nick</first_name>
        <last_name>Shortill</last_name>
        <position>LB</position>
        <ft.>6</ft.>
        <in.>2</in.>
        <weight>208</weight>
        <elig>1</elig>
        <faculty_program>Life Sciences</faculty_program>
        <year>1</year>
        <hometown>Nobleton On</hometown>
        <highschool>King City S S</highschool>
    </player>
    <player>
        <number>8</number>
        <first_name>Michael</first_name>
        <last_name>Daly</last_name>
        <position>DB</position>
        <ft.>6</ft.>
        <in.>1</in.>
        <weight>185</weight>
        <elig>3</elig>
        <faculty_program>Geography</faculty_program>
        <year>2</year>
        <hometown>Kitchener On</hometown>
        <highschool>Forest Heights C I</highschool>
    </player>
    <player>
        <number>9</number>
        <first_name>Allan</first_name>
        <last_name>Dicks</last_name>
        <position>DB</position>
        <ft.>5</ft.>
        <in.>9</in.>
        <weight>186</weight>
        <elig>2</elig>
        <faculty_program>Commerce</faculty_program>
        <year>2</year>
        <hometown>Abbotsford Bc</hometown>
        <highschool>W J Mouat S S</highschool>
    </player>
    <player>
        <number>10</number>
        <first_name>Brian</first_name>
        <last_name>Domenicucci</last_name>
        <position>DB</position>
        <ft.>6</ft.>
        <in.>3</in.>
        <weight>200</weight>
        <elig>2</elig>
        <faculty_program>H Kinesiology</faculty_program>
        <year>2</year>
        <hometown>Sherkston On</hometown>
        <highschool>Lakeshore Cath H S</highschool>
    </player>
    <player>
        <number>11</number>
        <first_name>Ben</first_name>
        <last_name>O\'Connor</last_name>
        <position>WR</position>
        <ft.>6</ft.>
        <in.>1</in.>
        <weight>185</weight>
        <elig>1</elig>
        <faculty_program>H Health Studies</faculty_program>
        <year>2</year>
        <hometown>Kingston On</hometown>
        <highschool>Frontenac S S</highschool>
    </player>
    <player>
        <number>12</number>
        <first_name>Kyle</first_name>
        <last_name>Quinlan</last_name>
        <position>QB</position>
        <ft.>6</ft.>
        <in.>3</in.>
        <weight>215</weight>
        <elig>4</elig>
        <faculty_program>H Economics</faculty_program>
        <year>3</year>
        <hometown>South Woodslee On</hometown>
        <highschool>Cardinal Carter S S</highschool>
    </player>
    <player>
        <number>13</number>
        <first_name>Shane</first_name>
        <last_name>Beaton</last_name>
        <position>LB</position>
        <ft.>5</ft.>
        <in.>11</in.>
        <weight>193</weight>
        <elig>4</elig>
        <faculty_program>Sociology</faculty_program>
        <year>3</year>
        <hometown>Brampton On</hometown>
        <highschool>Edmund Campion S S</highschool>
    </player>
    <player>
        <number>15</number>
        <first_name>Joseph</first_name>
        <last_name>Richardson</last_name>
        <position>LB</position>
        <ft.>6</ft.>
        <in.>1</in.>
        <weight>220</weight>
        <elig>1</elig>
        <faculty_program>Business</faculty_program>
        <year>1</year>
        <hometown>Waterdown On</hometown>
        <highschool>Waterdown Dist H S</highschool>
    </player>
    <player>
        <number>16</number>
        <first_name>Shaughn</first_name>
        <last_name>Reilly</last_name>
        <position>QB</position>
        <ft.>6</ft.>
        <in.>2</in.>
        <weight>170</weight>
        <elig>1</elig>
        <faculty_program>H Kinesiology</faculty_program>
        <year>4</year>
        <hometown>Grimsby On</hometown>
        <highschool>Blessed Trinity Cath S S</highschool>
    </player>
    <player>
        <number>17</number>
        <first_name>Brendan</first_name>
        <last_name>Fitzpatrick</last_name>
        <position>DB</position>
        <ft.>5</ft.>
        <in.>8</in.>
        <weight>155</weight>
        <elig>1</elig>
        <faculty_program>Social Sciences</faculty_program>
        <year>1</year>
        <hometown>Hamilton On</hometown>
        <highschool>Cardinal Newman S S</highschool>
    </player>
    <player>
        <number>18</number>
        <first_name>Joey</first_name>
        <last_name>Cupido</last_name>
        <position>DB</position>
        <ft.>5</ft.>
        <in.>10</in.>
        <weight>175</weight>
        <elig>3</elig>
        <faculty_program>H Kinesiology</faculty_program>
        <year>3</year>
        <hometown>Hamilton On</hometown>
        <highschool>St Jean De Brebeuf Cath S S</highschool>
    </player>
    <player>
        <number>19</number>
        <first_name>Jarred</first_name>
        <last_name>Jones</last_name>
        <position>WR</position>
        <ft.>6</ft.>
        <in.>1</in.>
        <weight>184</weight>
        <elig>5</elig>
        <faculty_program>Philosophy</faculty_program>
        <year>3</year>
        <hometown>Scarborough On</hometown>
        <highschool>Birchmount Park C I</highschool>
    </player>
    <player>
        <number>20</number>
        <first_name>Christopher</first_name>
        <last_name>Pezzetta</last_name>
        <position>RB</position>
        <ft.>5</ft.>
        <in.>10</in.>
        <weight>205</weight>
        <elig>1</elig>
        <faculty_program>Social Sciences</faculty_program>
        <year>1</year>
        <hometown>Burlington On</hometown>
        <highschool>Notre Dame Roman Cath S S</highschool>
    </player>
    <player>
        <number>20</number>
        <first_name>Andrew</first_name>
        <last_name>Sinclair</last_name>
        <position>WR</position>
        <ft.>5</ft.>
        <in.>11</in.>
        <weight>185</weight>
        <elig>1</elig>
        <faculty_program>Social Sciences</faculty_program>
        <year>1</year>
        <hometown>Denfield On</hometown>
        <highschool>Medway H S</highschool>
    </player>
    <player>
        <number>22</number>
        <first_name>James</first_name>
        <last_name>Hill</last_name>
        <position>RB</position>
        <ft.>5</ft.>
        <in.>10</in.>
        <weight>185</weight>
        <elig>2</elig>
        <faculty_program>Geography</faculty_program>
        <year>2</year>
        <hometown>Hamilton On</hometown>
        <highschool>Sir Allan Macnab S S</highschool>
    </player>
    <player>
        <number>23</number>
        <first_name>Gary</first_name>
        <last_name>Spero</last_name>
